### ISSUE TITLE
theblessing360 Gospel Page down

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#15]
Per Jackie - Please recover the gospel landing page on http://www.theblessing360.org/?page_id=2292&page=gospel.  You might be able to recover the page from a backup when they log in and re-create it and get it back up.

Here's the CMS login information:
http://theblessing360.org/wp-admin/
Username: cyrilrayan
Password: Genesis1:2$4321

**Comment by mikegillis677** [comment]
All done
