### ISSUE TITLE
Church on Fire Gospel Landing Page Down

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#16]
Per Jackie - The Church on Fire Gospel Landing Page is  downhttp://www.churchonfirecc.org/cvglobal/

Here's the CMS login information:
Site Name for Server Site Only w/ GoDaddy: www.tshirtpartiestexas.com 
 Host/IP/URL: 72.167.232.224 
 Username: thebestparties 
 Password: Soul061796deo
From the root...Go to folder name "Church"
NOTE: www.tshirtpartiestexas.com is the Server Site information with GoDaddy.  Our actual website is www.churchonfircc.org

**Comment by mikegillis677** [comment]
I can't get these login credentials to work.  There is no website at tshirtpartiestexas.com, and no login at 72.167.232.224.

If they want to do it themselves, they can just embed this HTML on their page and it will fix their problem:
```<div id="gmo-page-container"></div>
<script src="//glcdn.co/grant/js/gospel_0.js"></script>
```

**Comment by Cotrina9** [comment]
Try these credentials 

Site Name for Server Site Only w/ GoDaddy: www.tshirtpartiestexas.com 
 Host/IP/URL: 50.62.251.1 

 Username: thebestparties 
 Password: Soul061796deo
From the root...Go to folder name "Church"
NOTE: www.tshirtpartiestexas.com is the Server Site information with GoDaddy.  Our actual website is www.churchonfircc.org

**Comment by Cotrina9** [comment]
There was a typo in URL 
Our actual website is www.churchonfirecc.org

**Comment by mikegillis677** [comment]
Touhami says the CPanel login is at https://n3plcpnl0052.prod.ams3.secureserver.net:2083/cpsess6514174693/frontend/gl_paper_lantern/index.html?login=1&post_login=58104823046785 however, the credentials don't work there.

**Comment by mikegillis677** [comment]
Looks like they just used the embed code I provided and did it themselves.
