### ISSUE TITLE
Church On Fire Google Code Issue

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#26]
Per Jackie - Their website has issues with the Google code and Google is unable to verify what comes through.  It is affecting their campaigns.  Needs “emergency” maintenance so that we don’t lose their grant (we can’t get it to a 5% CTR without some immediate attention).  I’ve obtained the CMS credentials which are posted in the comments on the smartsheet.  Touhami needs to fix the code (maybe Sarah needs to run the conversion code again), and the webpage needs to link to their main webpage.  The issue is a technical one with Google that occurred because I don’t think Church on Fire set up their page/code exactly right, even though we provided it to them.  They aren’t technical enough to know.

**Comment by celant12** [comment]
The credentials did not work.
