### ISSUE TITLE
Hope Charities GO Grant

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#39]
Please set up Hope Charities with a Gospel Page for the Go Grant program.

**Comment by Cotrina9** [comment]
Update from Sarah - We have a new grant! Requesting for meeting to set up the gospel page (credentials and code are in smartsheets).

**Comment by Cotrina9** [comment]
This is one of Unite Life's Charities and they will be the first ones to go into the new flow of one button and sending the contact over to Unite Life and then having them send contacts that do not have a church within 50 miles back to us in ARC.  

We need to update the Gospel Presentation button and send over to Unite Life and then set up the process to accept referrals from them for new contacts.  We would like to be able to capture the new referrals at the Church level (Hope Charities) in addition to connecting them as a referral from Unite Life.
here is a landing page example - https://www.caringplace.tv/gospel . We ask for first name, last name, email, and phone number. Their location is also detected. 

I will also forward emails.....

**Comment by Cotrina9** [comment]
The credentials we received are bad so this is moving to Sprint 15 while we wait to receive good credentials.

**Comment by celant12** [comment]
login credentials did not work again. I Packaged the embed code and sent it to Jackie so their admin can embed it. If they need help they will let me know.

**Comment by Cotrina9** [comment]
Per Sarah - We are needing to switch Hope Charities back to our normal Hope gospel presentation.
