### ISSUE TITLE
Changes to GO Grants Website form

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#45]
Per Jackie - I need to add a field on the Get Started form for gogrants.org and ul.gogrants.org.  I've attached a visual, but I need a text field which is NOT required and is labeled Other Information.  

We are "assuming" some new, existing grants from referred nonprofits and they need a place to drop in their existing grant ad account ID.

![change to go grant website form](https://user-images.githubusercontent.com/32519187/43202061-f809124c-8fdf-11e8-8fc9-15af0ad545e2.png)

**Comment by celant12** [comment]
Done! and approved by Jackie
