### ISSUE TITLE
Fix gospel landing page for The Chapel

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#51]
Per Jackie - The gospel landing page for The Chapel only has one picture on the page.  Something has happened to the other pictures that go with the text.  Can you please have Touhami fix the page?  CMS credentials are in the GO Grants Handoff smartsheet (line 17) for The Chapel.

**Comment by celant12** [comment]
Tried to access the Chapel CMS but the credentials did not work. Jackie ask me to send her the packaged code and she will send it to their tech team.
I sent the packaged code to Jackie.

**Comment by Cotrina9** [comment]
Per Jackie - The creds do not work.  We've contacted them to place the code on the page, but it isn't correct.  I've contacted their tech and asked for temporary credentials for Touhami.  I'm waiting for a reply, so please leave this open until we hear back and Touhami can then access and correct the page.

**Comment by celant12** [comment]
Used the new credentials but all I can do is upload photos to their server. This was not helpful. I sent Jackie this info for them to make the updates:
Here are the link for the 3 photos they need to update in the html of the Gospel Page:
//cvoutreach.com/lp/gmo/jesus1.jpg	—> https://a.glcdn.co/images/gospel/arrow-god-s-love.jpg
//cvoutreach.com/lp/gmo/prayer1.jpg	—> https://a.glcdn.co/images/gospel/sin-nature.jpg
//cvoutreach.com/lp/gmo/jesus2.jpg	—> https://a.glcdn.co/images/gospel/god-s-plan.jpg

This is all they need to change for the photos to be displayed. If they want to put them on their own server, they can downloads and upload them to their server and style them any way they want.

**Comment by celant12** [comment]
Jackie contacted them. They gave me access. I looked at the code and found out that they are using an old code.
I had to go to GodLife repo and update the Gospel Presentation code and push it to dev then to production.
