### ISSUE TITLE
GO Grant Website Update

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#52]
Per Jackie - Touhami,
In preparation for the "promotion" of our website, gogrants.org, I'd like to put all the content of the How It Works section at the bottom of the Home page.  We talked about this so that if someone gets on the homepage, they can scroll through all the content.  You can leave How It Works as a tab and separate page as well, but can you append it to the home page so the sections scroll down through all the content.  I think it will be critical to have this format when we promote the page (within the next two weeks).
Please let me review it before it goes live.
Thank you,
Jackie

**Comment by celant12** [comment]
Made the update. Jackie reviewed the changes and approved them. Pushed to production.
