### ISSUE TITLE
Switch conversion code for Global Advance

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#54]
Per Sarah - I'm having to switch Global Advance back to it's cancelled account in order to submit it for review. I need to swap out the Google conversion code to correlate with this account.

**Comment by celant12** [comment]
Got the new conversion tracking code from Sarah. Updated the code on the Gospel Page.

**Comment by celant12** [comment]
Sarah Wallace [4:01 PM]
Global advance tag is confirmed. You can close the ticket
