### ISSUE TITLE
GO Program Email Address

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#56]
Per Kathy - We need to make the GO Program email address match the Go Program URL.
I would like you to create an email (go@gogrants.org)  that forwards to the current email:  go@gmomail.org

It is critical that I know IF you can meet the request. Then we will have 7 -10 days to get it done.

Please let me know right away if this request can be done. Then, we can set a date for completion.

**Comment by celant12** [comment]
I finished working on this one. I created the forward with DNS Made Easy but it did not work as I hoped so I created the forward with GoDaddy and added MX Records in DNS Made Easy.

**Comment by celant12** [comment]
Tested it with Jackie and it working properly.
