### ISSUE TITLE
Gospel landing/contact page font size for The Chapel

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#57]
Per Jackie - Please increase the font size on the field heading on the gospel contact landing page for The Chapel.  Credentials for access to The Chapel are found in the GO Grants Handoff smartsheet.

I've attached a picture of what I'm talking about.

**Comment by Cotrina9** [comment]
![the chapel contact info submission form](https://user-images.githubusercontent.com/32519187/46586213-c6fd3200-ca40-11e8-841d-9753ec629e09.png)

**Comment by celant12** [comment]
I am sorry I tried but the credentials are no longer valid. Please ask for time extension or new login. Thanks

**Comment by celant12** [comment]
Credentials did not work. Asked for new credentials

**Comment by celant12** [comment]
Touhami Attar [3:16 PM]

I am sorry Jackie the Chapel CMS credentials are not working for me I even tried to reset the password. The reset went through but still did not log me in

Jackie Westbrook [3:23 PM]
Are you trying to change the font size on the form? If so, just abandon that effort. I don’t have time to chase them! Could they do it themselves?

Touhami Attar [3:31 PM]
Yes. They could do it themselves if they want to.

Jackie Westbrook [3:32 PM]
Ok, that’s what I’m going to tell them.  They can work with their own people to get it done.
