### ISSUE TITLE
SOCO Church

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#58]
SOCO Church is ready for the Gospel Presentation for GO Grants Program.  They want the 4 steps IPA (one button if we have it in the UL version).  Conversion Code is in attachments on the GO Grant Handoff SmartSheet.  URL - http://www.soco.church.

**Comment by celant12** [comment]
Credentials did not work. Asked for new credentials

**Comment by celant12** [comment]
This is done. May need to change the background in the future.
