### ISSUE TITLE
Fixing Google Grant Account

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#59]
Per Jason - I need to fix conversion tracking in order to get our account up and running again.

**Comment by celant12** [comment]
I updated the tracking code. Based on Jason's request I replaced MW codes with the ones he provided.

**Comment by Cotrina9** [comment]
This is just waiting for verification from Jason before being pushed.

**Comment by celant12** [comment]
Jason confirmed that the account is back up and running.
