### ISSUE TITLE
Update donation page on The Potter's Ministries website

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#61]
Per Jackie - Please update the Potter's Ministries website with the following statement on their donation webpage (required by Google).  I received an email with the pastor's permission to do this update to help get them into compliance while they are looking into the issue of slow loading of their site.

The Potter's Ministries is an exempt organization as described in Section 501(c)(3) of the Internal Revenue Code. EIN 52-2374607

Their CMS credentials are found in GO Grants Handoff smartsheet as an attachment (not as a comment).  Put this into whatever sprint works.

**Comment by celant12** [comment]
I added the the statement to the page and Jackie approved it.
