### ISSUE TITLE
Hebrew stats and google code

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#62]
Per Sarah - Please add stats code and google code to the Hebrew landing page.

FYI - They have already been asking for results today....

**Comment by celant12** [comment]
We are experiencing a lot of issues because we don't have access to the backend of the partners site. We have tried few possible ways of adding the conversion tracking but they did not work. We will try couple more.

**Comment by celant12** [comment]
Sarah is fine with the tracking we got working on GMOStats
