### ISSUE TITLE
Update conversion tag on Mission Maasai

### ISSUE THREAD

**Issue by Cotrina9** [gmo/grant#63]
Per Sarah - Google has suspended Mission Maasai for not having a "meaningful" conversion set up since it's set for a page load instead of a click.  Please update (cms creds on smartsheet) conversion code with the new attached one.  Thanks!

[Event snippet - Form Submit (2).txt](https://github.com/gmo/grant/files/2473115/Event.snippet.-.Form.Submit.2.txt)

**Comment by celant12** [comment]
Code tracking Label changed
